sudo: false

language: node.js

node_js:
  - node

install:
  - cd 2
  - npm install
  - cd ../3
  - npm install
  - cd ..

script:
  - cd 2
  - npm test
  - cd ../3
  - npm test

notifications:
  email:
  - chuvantinh1991@gmail.com
