sudo: false

language: node.js

node_js:
  - node

install:
  - cd 2
  - npm install
  - cd ../3
  - npm install
  - cd ..

  - cd 5/backend
  - npm install
  - cd ..
  - cd 5/web
  - npm install

script:
  - cd 2
  - npm test
  - cd ../3
  - npm test
  - cd ..

  - cd 5/backend
  - npm test
  - cd ..
  - cd 5/web
  - npm run dev
  - cd ..
  - cd ..

notifications:
  email:
  - chuvantinh1991@gmail.com


